import { assessFinancialAction } from "./financial-risk.js";

/** Golden deterministic risk calculation; no database, credential or provider mutation. */
export function financialRiskEngineHealthy(now: Date) {
  const timestamp = now.toISOString();
  const expiry = new Date(now.getTime() + 60000).toISOString();
  const assessment = assessFinancialAction({
    now,
    action: {
      version: 1,
      mode: "LIVE",
      provider: "fixture",
      accountId: "health",
      instrumentId: "health-symbol",
      brokerSymbol: "HEALTH",
      operation: "OPEN",
      side: "BUY",
      orderType: "MARKET",
      volume: "1",
      price: null,
      stopLimitPrice: null,
      stopLoss: "100",
      takeProfit: null,
      expiresAt: null,
      fillingMode: null,
    },
    envelope: {
      version: 1,
      ownerId: "health-owner",
      botId: "health-agent",
      accountId: "health",
      mode: "LIVE",
      expiresAt: expiry,
      allowedInstruments: ["health-symbol"],
      allowedOperations: ["OPEN"],
      maxMissionLoss: "100",
      maxOpenRisk: "50",
      maxRiskPerTrade: "10",
      maxConcurrentPositions: 1,
      maxPendingOrders: 1,
      breachBehavior: "FREEZE",
      expiryBehavior: "FREEZE",
      targetBehavior: "FREEZE",
      currency: "USD",
      allocatedCapital: "1000",
      maxNotional: "1000",
      maxMarginUsagePercent: "50",
      maxDailyLoss: null,
      allowedOrderTypes: ["MARKET"],
      riskIncreasePermissions: [],
      supervisionPositionId: null,
      supervisedOrderIds: [],
      riskCalculationVersion: "stop-loss-v1",
      costReservePerTrade: "1",
    },
    facts: {
      version: 1,
      accountId: "health",
      instrumentId: "health-symbol",
      brokerSymbol: "HEALTH",
      currency: "USD",
      connected: true,
      tradingAllowed: true,
      accountMode: "HEDGING",
      observedAt: timestamp,
      equity: "1000",
      margin: "0",
      freeMargin: "1000",
      quote: {
        version: 1,
        provider: "fixture",
        accountId: "health",
        instrumentId: "health-symbol",
        brokerSymbol: "HEALTH",
        bid: "101",
        ask: "101",
        sourceTime: timestamp,
        receivedAt: timestamp,
        revision: "health",
      },
      tickSize: "1",
      lossTickValue: "1",
      contractSize: "1",
      profitCurrency: "USD",
      minVolume: "1",
      maxVolume: "10",
      volumeStep: "1",
      digits: 0,
      stopsLevel: 0,
      symbolTradingAllowed: true,
      specificationObservedAt: timestamp,
      orderTypes: ["MARKET"],
      partialClose: false,
      proposedMargin: "1",
      openPositions: [],
      pendingOrders: [],
    },
    state: {
      version: 1,
      missionPnl: "0",
      dailyPnl: "0",
      openRisk: "0",
      openNotional: "0",
      positions: 0,
      pendingOrders: 0,
      unresolvedEffects: false,
      missionActive: true,
      accountFrozen: false,
    },
  });
  return (
    assessment.decision === "ALLOW" &&
    assessment.riskAfter === "2" &&
    assessment.incrementalRisk === "2" &&
    assessment.notional === "101" &&
    assessment.margin === "1"
  );
}
